api_version = "2024-01"

[[extensions]]
name = "thank-you-upsell"
type = "ui_extension"
handle = "thank-you-upsell"

[[extensions.targeting]]
module = "./src/ThankYou.tsx"
target = "purchase.thank.you.block.render"

[extensions.capabilities]
network_access = true
